In [1]:
import torch

In [2]:
x = torch.Tensor([5, 3])     # Tensor bi bio odprilike samo naziv za visedimenzionalni array
y = torch.Tensor([2, 1])

x*y

tensor([10.,  3.])

In [3]:
a = torch.zeros([2, 5])      # torch.zeros funkcija je ocito kao u octaveu funkcija zeros
print(a)
print(a.shape)
b = torch.rand([2,3])
b

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.Size([2, 5])


tensor([[0.2701, 0.9321, 0.9203],
        [0.8644, 0.0881, 0.2230]])

In [4]:
c = b.view([1, 6])        # ova funkcija u numpy ili tensorflow je reshape
c

tensor([[0.2701, 0.9321, 0.9203, 0.8644, 0.0881, 0.2230]])

In [5]:
pip install jupyterthemes

Note: you may need to restart the kernel to use updated packages.


In [6]:
! jt -h

usage: jt [-h] [-l] [-t THEME] [-f MONOFONT] [-fs MONOSIZE] [-nf NBFONT]
          [-nfs NBFONTSIZE] [-tf TCFONT] [-tfs TCFONTSIZE] [-dfs DFFONTSIZE]
          [-ofs OUTFONTSIZE] [-mathfs MATHFONTSIZE] [-m MARGINS]
          [-cursw CURSORWIDTH] [-cursc CURSORCOLOR] [-cellw CELLWIDTH]
          [-lineh LINEHEIGHT] [-altp] [-altmd] [-altout] [-P] [-T] [-N] [-kl]
          [-vim] [-r] [-dfonts]

optional arguments:
  -h, --help            show this help message and exit
  -l, --list            list available themes
  -t THEME, --theme THEME
                        theme name to install
  -f MONOFONT, --monofont MONOFONT
                        monospace code font
  -fs MONOSIZE, --monosize MONOSIZE
                        code font-size
  -nf NBFONT, --nbfont NBFONT
                        notebook font
  -nfs NBFONTSIZE, --nbfontsize NBFONTSIZE
                        notebook fontsize
  -tf TCFONT, --tcfont TCFONT
                        txtcell font
  -tfs TCFONTSIZE, --tcfontsize TCF

In [7]:
! jt -l

Available Themes: 
   chesterish
   grade3
   gruvboxd
   gruvboxl
   monokai
   oceans16
   onedork
   solarizedd
   solarizedl


In [14]:
! jt -t chesterish -T -N -kl

In [15]:
! jt -t grade3 -T -N -kl

In [8]:
! jt -t gruvboxd -T -N -kl

In [3]:
! jt -t gruvboxl -T -N -kl

In [5]:
! jt -t monokai -T -N -kl

In [4]:
! jt -t oceans16 -T -N -kl

In [13]:
! jt -t onedork -T -N -kl

In [7]:
! jt -t solarizedd -T -N -kl

In [8]:
! jt -t solarizedl -T -N -kl

In [17]:
! jt -r 

Reset css and font defaults in:
C:\Users\Agata\.jupyter\custom &
C:\Users\Agata\AppData\Roaming\jupyter\nbextensions
