In [1]:
import torch

### Tensors
At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix or any n-dimensional array. Let's create a tensor with a single number:

In [2]:
# Number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [4]:
# Matrix
t3 = torch.tensor([[5, 6], [7, 8], [9, 10]])
t3

tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [5]:
# 3-dimensional array
t4 = torch.tensor([[[11, 12, 13], [14, 15, 16]], [[17, 19, 20], [13, 16, 19]]])
t4

tensor([[[11, 12, 13],
         [14, 15, 16]],

        [[17, 19, 20],
         [13, 16, 19]]])

In [6]:
# razlika tensora i običnih listi je ta sto ako u tensoru radim matricu od dva vektora iste duljine 
# i npr treci od razlicite duljine dobijem error
# tj. tensor treba imat pravilnost

In [7]:
print(t1.shape)    # ako krenes od vanjske zagrade tensora i brojis koliko elemenata ima i tako prema unutra
print(t2.shape)
print(t3.shape)
print(t4.shape)

torch.Size([])
torch.Size([4])
torch.Size([3, 2])
torch.Size([2, 2, 3])


### Tensor operations and gradients
We can combine tensors with the usual arithmetic operations. Let's look an example:

In [8]:
# Create tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(5., requires_grad = True)

We'we created 3 tensors x, w and b, all numbers. w and b have an additional parameter requires_grad det to True. We'll see what it does in just a moment.
Let's create a new tensor y by combining these tensors:

In [9]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, y is a tensor with the value 3*4+5=17. What makes PyTorch special is that we can automatically compute the derivative of y w.r.t.the tensors that have requires_grad ste True i.e. w and b. To compute the derivatives, we can call the .backward method on our result y.

In [10]:
# Compute derivatives
y.backward()
y

C:\Users\Agata\Anaconda3\lib\site-packages\torch\autograd\__init__.py:145: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:109.)
  Variable._execution_engine.run_backward(


tensor(17., grad_fn=<AddBackward0>)

The derivatives od y w.r.t. the input tensors are stored in the .grad property of the respective tensors.

In [11]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


As expected, dy/dw has the same value as x i.e. 3, and dy/db has the value 1. Note that x.grad is None, because x doesn't have requires_grad set to True.
The 'grad' in w.grad stands for gradient, which is another term for derivative, used mainly when dealing with matrices.

### Interoperability with numpy
Numpy is a popular open source library used for mathematical and scientific computing in Python. It enables efficient operations on large multi-dimensional arrays, and has a large ecosystem of supporting libraries.


Matplotlib for plotting and visualisation;
OpenCV for image and video processing;
Pandas for file I/O and data analysis


Instead of reinventing the wheel, PyTorch interoperates really well with with Numpy levreage its existing ecosystem of tools and libraries.


Here is how we create an array in Numpy:

In [13]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

We can convert a Numpy array to a PyTorch tensor using torch.form_numpy.

In [14]:
# Convert Numpy array to a torch tensor.
y = torch.tensor(x)
y

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

Let's verify that the numpy array and torch tensor have similar data types.

In [15]:
x.dtype, y.dtype

(dtype('int32'), torch.int32)

We can convert a PyTorch tensor to a Numpy array using the .numpy method of an tensor.

In [16]:
# Convert a torch tensor to a numpy array.
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

The interoperability between PyTorch and Numpy is really important because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.

### Commit and upload the notebook
Na jovianu mogu objavljivat svoj kod itd

### Further Reading
Tensors in PyTorch support a variety of operations, and what we've covered here is by no means exhaustive. You can learn more about tensors and tensor operations here: [https://pytorch.org/docs/stable/tensors.html]

You can take advantage of the interactive jupyter enviroment to experiment with tensors and try different combinations of operations discussed above. Here are some things to try out:
1.What if one or more x, w or b were matrices, instead of numbers, in the above example?
2.What if y was a matrix created using torch.tensor, with each element of the matrix expressed as a combination of numeric tensors x, w and b?
3.What if we had a chain of operations instead of just one i.e. y = x * w + b, z = 1 * y + m, w = c * z + d and so on? What would calling w.grad do?